SELECT CITY, LENGTH(CITY) AS CITY_LENGTH
FROM STATION
WHERE CITY = (SELECT CITY FROM STATION ORDER BY LENGTH(CITY), CITY ASC LIMIT 1)
   OR CITY = (SELECT CITY FROM STATION ORDER BY LENGTH(CITY) DESC, CITY ASC LIMIT 1);
